from __future__ import annotations

from ..schemas.base import RawReference
from ..schemas.cpu import CpuSpec
from ..schemas.gpu import ApiSupport, GpuSpec
from ..schemas.model import ArchitectureHint, InferenceInfo, ModelSpec, PopularityInfo, VariantSpec, WeightsInfo


def cpu_seed_specs() -> list[CpuSpec]:
    return [
        CpuSpec(
            canonical_name="AMD Ryzen 9 7950X",
            aliases=["ryzen 9 7950x"],
            vendor="amd",
            family="Ryzen 9",
            model="7950X",
            cores=16,
            threads=32,
            base_clock_ghz=4.5,
            boost_clock_ghz=5.7,
            l3_cache_mb=64.0,
            tdp_w=170,
            codename="Raphael",
            socket="AM5",
            release="Q3 2022",
            source_url="https://en.wikipedia.org/wiki/List_of_AMD_Ryzen_processors",
            raw_ref=RawReference(cache_key="data/raw_cache/wiki/cpu/amd-ryzen-seed.json"),
        ),
        CpuSpec(
            canonical_name="AMD Ryzen 7 5800X3D",
            aliases=["ryzen 7 5800x3d"],
            vendor="amd",
            family="Ryzen 7",
            model="5800X3D",
            cores=8,
            threads=16,
            base_clock_ghz=3.4,
            boost_clock_ghz=4.5,
            l3_cache_mb=96.0,
            tdp_w=105,
            codename="Vermeer",
            socket="AM4",
            release="Q1 2022",
            source_url="https://en.wikipedia.org/wiki/List_of_AMD_Ryzen_processors",
            raw_ref=RawReference(cache_key="data/raw_cache/wiki/cpu/amd-ryzen-seed.json"),
        ),
        CpuSpec(
            canonical_name="Intel Core i7-8086K",
            aliases=["core i7 8086k", "i7-8086k"],
            vendor="intel",
            family="Core i7",
            model="8086K",
            cores=6,
            threads=12,
            base_clock_ghz=4.0,
            boost_clock_ghz=5.0,
            l3_cache_mb=12.0,
            tdp_w=95,
            codename="Coffee Lake",
            socket="LGA 1151",
            release="Q2 2018",
            source_url="https://en.wikipedia.org/wiki/List_of_Intel_processors",
            raw_ref=RawReference(cache_key="data/raw_cache/wiki/cpu/intel-seed.json"),
        ),
    ]


def gpu_seed_specs() -> list[GpuSpec]:
    return [
        GpuSpec(
            canonical_name="NVIDIA GeForce RTX 4090",
            aliases=["rtx 4090", "geforce rtx 4090"],
            vendor="nvidia",
            product_line="GeForce",
            architecture="Ada Lovelace",
            codename="AD102",
            process_nm=4,
            bus_interface="PCIe 4.0 x16",
            memory_size_gib=24,
            memory_bus_width_bit=384,
            memory_bandwidth_gbs=1008.0,
            tdp_w=450,
            api_support=ApiSupport(vulkan="1.x", direct3d="12", opengl="4.x"),
            cuda_compute_capability="8.9",
            processing_power_fp32_gflops=82600.0,
            processing_power_fp16_gflops=165200.0,
            processing_power_bf16_gflops=165200.0,
            processing_power_int8_gops=1321600.0,
            source_url="https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units",
            raw_ref=RawReference(cache_key="data/raw_cache/wiki/gpu/nvidia-seed.json"),
        ),
        GpuSpec(
            canonical_name="NVIDIA GeForce RTX 3090",
            aliases=["rtx 3090", "geforce rtx 3090"],
            vendor="nvidia",
            product_line="GeForce",
            architecture="Ampere",
            codename="GA102",
            process_nm=8,
            bus_interface="PCIe 4.0 x16",
            memory_size_gib=24,
            memory_bus_width_bit=384,
            memory_bandwidth_gbs=936.0,
            tdp_w=350,
            api_support=ApiSupport(vulkan="1.x", direct3d="12", opengl="4.x"),
            cuda_compute_capability="8.6",
            processing_power_fp32_gflops=35600.0,
            source_url="https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units",
            raw_ref=RawReference(cache_key="data/raw_cache/wiki/gpu/nvidia-seed.json"),
        ),
        GpuSpec(
            canonical_name="NVIDIA GeForce RTX 4070 SUPER",
            aliases=["rtx 4070 super", "geforce rtx 4070 super"],
            vendor="nvidia",
            product_line="GeForce",
            architecture="Ada Lovelace",
            codename="AD104",
            process_nm=5,
            bus_interface="PCIe 4.0 x16",
            memory_size_gib=12,
            memory_bus_width_bit=192,
            memory_bandwidth_gbs=504.0,
            tdp_w=220,
            api_support=ApiSupport(vulkan="1.x", direct3d="12", opengl="4.x"),
            cuda_compute_capability="8.9",
            processing_power_fp32_gflops=35800.0,
            source_url="https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units",
            raw_ref=RawReference(cache_key="data/raw_cache/wiki/gpu/nvidia-seed.json"),
        ),
        GpuSpec(
            canonical_name="AMD Radeon RX 7900 XTX",
            aliases=["rx 7900 xtx", "radeon rx 7900 xtx"],
            vendor="amd",
            product_line="Radeon",
            architecture="RDNA 3",
            codename="Navi 31",
            process_nm=5,
            bus_interface="PCIe 4.0 x16",
            memory_size_gib=24,
            memory_bus_width_bit=384,
            memory_bandwidth_gbs=960.0,
            tdp_w=355,
            api_support=ApiSupport(vulkan="1.x", direct3d="12", opengl="4.x"),
            processing_power_fp32_gflops=61400.0,
            source_url="https://en.wikipedia.org/wiki/List_of_AMD_graphics_processing_units",
            raw_ref=RawReference(cache_key="data/raw_cache/wiki/gpu/amd-seed.json"),
        ),
    ]


def model_seed_specs(hf_repo_id: str | None = None) -> list[ModelSpec]:
    items = [
        ModelSpec(
            canonical_name="Qwen/Qwen2.5-7B-Instruct@bf16",
            aliases=["Qwen2.5-7B-Instruct", "qwen2.5 7b instruct bf16"],
            source_url="https://huggingface.co/Qwen/Qwen2.5-7B-Instruct",
            hf_repo_id="Qwen/Qwen2.5-7B-Instruct",
            variant=VariantSpec(precision="bf16", format="safetensors"),
            task="text-generation",
            license_id="apache-2.0",
            inference=InferenceInfo(provider_required=True, status="warm"),
            declared_context_tokens=32768,
            architecture_hint=ArchitectureHint(
                model_type="qwen2",
                num_layers=28,
                hidden_size=3584,
                num_attention_heads=28,
                num_kv_heads=4,
                vocab_size=152064,
            ),
            num_parameters=7_610_000_000,
            weights=WeightsInfo(total_size_bytes=15_220_000_000),
            popularity=PopularityInfo(downloads_30d=500_000, likes=10_000),
            raw_ref=RawReference(cache_key="data/raw_cache/huggingface/model/qwen-7b-seed.json"),
        ),
        ModelSpec(
            canonical_name="Qwen/Qwen2.5-7B-Instruct@q4_k_m",
            aliases=["Qwen2.5-7B-Instruct-GGUF", "qwen2.5 7b instruct q4_k_m"],
            source_url="https://huggingface.co/Qwen/Qwen2.5-7B-Instruct-GGUF",
            hf_repo_id="Qwen/Qwen2.5-7B-Instruct-GGUF",
            variant=VariantSpec(quantization="q4_k_m", format="gguf"),
            task="text-generation",
            license_id="apache-2.0",
            inference=InferenceInfo(provider_required=False, status="warm"),
            declared_context_tokens=32768,
            architecture_hint=ArchitectureHint(
                model_type="qwen2",
                num_layers=28,
                hidden_size=3584,
                num_attention_heads=28,
                num_kv_heads=4,
                vocab_size=152064,
            ),
            num_parameters=7_610_000_000,
            weights=WeightsInfo(total_size_bytes=4_700_000_000),
            popularity=PopularityInfo(downloads_30d=150_000, likes=3_000),
            raw_ref=RawReference(cache_key="data/raw_cache/huggingface/model/qwen-7b-gguf-seed.json"),
        ),
        ModelSpec(
            canonical_name="deepseek-ai/DeepSeek-R1@bf16",
            aliases=["DeepSeek-R1", "deepseek r1 bf16"],
            source_url="https://huggingface.co/deepseek-ai/DeepSeek-R1",
            hf_repo_id="deepseek-ai/DeepSeek-R1",
            variant=VariantSpec(precision="bf16", format="safetensors"),
            task="text-generation",
            license_id="apache-2.0",
            inference=InferenceInfo(provider_required=True, status="warm"),
            declared_context_tokens=32768,
            architecture_hint=ArchitectureHint(
                model_type="llama",
                num_layers=80,
                hidden_size=8192,
                num_attention_heads=64,
                num_kv_heads=8,
                vocab_size=128000,
            ),
            num_parameters=70_000_000_000,
            weights=WeightsInfo(total_size_bytes=140_000_000_000),
            popularity=PopularityInfo(downloads_30d=200_000, likes=15_000),
            raw_ref=RawReference(cache_key="data/raw_cache/huggingface/model/deepseek-r1-seed.json"),
        ),
    ]
    if hf_repo_id is None:
        return items
    return [item for item in items if item.hf_repo_id == hf_repo_id or item.canonical_name == hf_repo_id]
